### ISSUE TITLE
First attempt at contributing - adding some concepts from Jim Collins Good to Great

### ISSUE THREAD

**Issue by SteveMcMichael2022** [CyberRiskOp/CHMH#74]
Hello, I found the contributor expectations section (here https://github.com/CyberRiskOp/CHMH/issues/67#how-to-contribute) after attempting to add some content here: https://github.com/CyberRiskOp/CHMH/pull/73

Some mistakes with my first attempt are:

1. Committing directly to the master branch instead of the development branch - not sure how to change
2. I didn't make an issue in advance - creating this one now.

As noted in my commit I'm wide open to feedback on whether you think this content is a good fit or not.  

Thanks

**Comment by KipBoyle** [comment]
It's a great fit! Thanks!
